# Generated by Django 6.0.3 on 2026-03-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=32, unique=True)),
                ('broadcaster', models.CharField(max_length=128)),
                ('video_url', models.URLField(blank=True, max_length=1024)),
                ('playback_time', models.FloatField(default=0.0)),
                ('is_playing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_id', models.CharField(max_length=128)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='synchronizer_app.room')),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('room', 'listener_id')},
            },
        ),
    ]
