# Generated by Django 6.0.3 on 2026-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='broadcaster',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
