# Generated by Django 6.0.3 on 2026-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer_app', '0002_alter_room_broadcaster_alter_room_room_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
