# Generated by Django 6.0.3 on 2026-03-13 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer_app', '0004_room_latest_message_room_media_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listener',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='listener',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='room',
            name='broadcaster',
        ),
        migrations.RemoveField(
            model_name='room',
            name='latest_message',
        ),
        migrations.RemoveField(
            model_name='room',
            name='media_mode',
        ),
        migrations.RemoveField(
            model_name='room',
            name='state_updated_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='listener',
            name='listener_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='video_url',
            field=models.TextField(blank=True),
        ),
    ]
