# Generated by Django 6.0.3 on 2026-03-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchronizer_app', '0005_alter_listener_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='broadcaster',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='latest_message',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='room',
            name='listener_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='media_mode',
            field=models.CharField(blank=True, default='video_url', max_length=32),
        ),
    ]
